Fixed a misleading variable name in the doc for enabling the ui
jsok/puppet-vault pull request #123
Opened 2018-05-23 16:26 UTC by mvisonneau

Just a documentation change in order to fix a typo.

2018-05-23 21:23 UTC, jsok requested changes

2018-05-23 21:23 UTC, jsok commented on README.md
> +* `enable_ui`: Enable the vault UI (requires vault 0.10.0+ or Enterprise) (default: `undef`)
It is `ui` to match the actual configuration option: https://www.vaultproject.io/docs/configuration/index.html#ui

2018-05-23 21:53 UTC, mvisonneau commented on README.md
> +* `enable_ui`: Enable the vault UI (requires vault 0.10.0+ or Enterprise) (default: `undef`)
alright, I updated it to be coherent then 👌

2018-06-11 03:30 UTC, ojongerius commented
@jsok good to merge?

2018-06-11 03:57 UTC, closed without merging

2018-06-11 03:58 UTC, jsok commented
I completely misunderstood the original PR, asking for the change was not necessary. Apologies @mvisonneau . I've pushed the fix to master just now.

2018-06-12 07:10 UTC, mvisonneau commented
no worries, thanks @jsok