making sure the repo gets configured first
jsok/puppet-vault pull request #178
Opened 2021-01-16 21:38 UTC by attachmentgenie

##### SUMMARY
make sure that the repo is configured befor the package

2021-01-16 22:40 UTC, jsok requested changes

2021-01-16 22:40 UTC, jsok commented on manifests/install.pp
> +        Class['hashi_stack::repo'] -> Package[ $::vault::package_name]
```suggestion
        Class['hashi_stack::repo'] -> Package[$::vault::package_name]
```

2021-01-17 10:49 UTC, attachmentgenie commented on manifests/install.pp
> +        Class['hashi_stack::repo'] -> Package[ $::vault::package_name]
changed and pushed

2021-01-17 21:06 UTC, jsok approved these changes

2021-01-17 21:07 UTC, merged