base cap_ipc_lock on file instead of file notify
jsok/puppet-vault pull request #49
Opened 2016-11-01 15:21 UTC by cruwe

To be allowed to use the mlock option when running vault with the
permission of a user other than root, such as 'vault', the
binary (/usr/local/bin/)vault needs to have the cap_ipc_lock capability
set.

Currently, the capabilities are refreshed only when the binary
changes. Failures to set the capability are reported once and ignored
afterwards.

Making the exec-resource which sets the capability depend on a
test-condition instead of a change of the binary makes puppet check the
capabilites on the file on each run and changes the capability if
cap_ipc_lock is missing on the file.

(tested on test-kitchen using privileged lxd containers running CentOS7. Please excuse my fat fingers and the noise.)

	modified:   manifests/install.pp

2016-11-01 15:37 UTC, crayfishx commented on manifests/install.pp
>      exec { "setcap cap_ipc_lock=+ep ${vault_bin}":
I like the idea behind this PR, it should be a maintained state, not a one off...  There is a nice alternative to doing this in an exec though...

https://forge.puppet.com/stm/file_capability

@cruwe / @jsok what do you think about using that?  It looks like a nicer way to me.

2016-11-01 21:01 UTC, jsok commented on manifests/install.pp
> +      unless    => 'getcap /usr/local/bin/vault | grep cap_ipc_lock+ep',
This path would need to reference the `$vault_bin` variable rather than a hardcoded path.

2016-11-01 21:11 UTC, jsok requested changes

2016-11-01 21:11 UTC, jsok commented on manifests/install.pp
>      exec { "setcap cap_ipc_lock=+ep ${vault_bin}":
Agree that it's a nicer alternative, I've opened #50 to track the issue.

@cruwe If you just want to get the functionality working in this PR I'm happy to merge as-is (once tests are passing), but you're also free to tackle #50 if you feel like it.

2016-11-02 15:49 UTC, cruwe commented on manifests/install.pp
>      exec { "setcap cap_ipc_lock=+ep ${vault_bin}":
My apologies for the noise I caused ... Repeatedly, I was unable to run the tests travis-ci does locally. bundle exec rake spec throws 25 failures where travis completes without any.

Depending on how my workload develops during the week, I will work on #50. Thank you for your work on puppet-vault!

2016-11-02 15:51 UTC, cruwe commented on manifests/install.pp
>      exec { "setcap cap_ipc_lock=+ep ${vault_bin}":
btw, would you like me to do a git rebase -i on the commits I did to get the tests passing or do you prefer the have them individually?

2016-11-02 20:49 UTC, jsok approved these changes

2016-11-02 20:51 UTC, jsok commented on manifests/install.pp
>      exec { "setcap cap_ipc_lock=+ep ${vault_bin}":
Commits are fine, there's not too many.

Chances are you weren't setting the right env vars for the tests, e.g.:

```
env STRICT_VARIABLES="no" bundle exec rake spec
```

2016-11-02 20:52 UTC, merged

2016-11-03 07:17 UTC, cruwe commented on manifests/install.pp
>      exec { "setcap cap_ipc_lock=+ep ${vault_bin}":
Thanks for the merge and your work on puppet-vault. Cheers!